In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [3]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
type(a)

numpy.ndarray

In [5]:
b = np.array([9,8,7,6,5,4,3,2,1])
a+b

array([10, 10, 10, 10, 10, 10, 10, 10, 10])

In [6]:
a-b

array([-8, -6, -4, -2,  0,  2,  4,  6,  8])

In [7]:
a*b

array([ 9, 16, 21, 24, 25, 24, 21, 16,  9])

In [9]:
np.dot(a,b)

np.int64(165)

In [10]:
a++

SyntaxError: invalid syntax (1277751513.py, line 1)

In [11]:
a+a - b+b

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
np.max(a)

np.int64(9)

In [13]:
max(a)

np.int64(9)

In [14]:
min a

SyntaxError: invalid syntax (264354883.py, line 1)

In [15]:
min(a)

np.int64(1)

In [16]:
np.avg(a)

AttributeError: module 'numpy' has no attribute 'avg'

In [17]:
avg(a)

NameError: name 'avg' is not defined

In [18]:
a.avg()

AttributeError: 'numpy.ndarray' object has no attribute 'avg'